### ISSUE TITLE
全局配置了headers，但是无效

### ISSUE THREAD

**Issue by ctocode** [dream2023/vue-ele-form-quill-editor#5]
'quill-editor': {
        headers: {
            'token': 'asdasdas',
        },
        // 比如设置上传 action 后, 所有的 quill-editor 编辑器上传图片都会采用这个属性
        action:   '/uploadImage',
        // 附带的参数,
        responseFn(response, file) { // 处理响应结果
            console.log('xxx');
            return response.save_url;
        },
    },

**Comment by dream2023** [comment]
我这边设置是有效的，如果问题请再次评论
